### ISSUE TITLE
Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by ephimoff** [docpad/docpad-plugin-paged#15]
Hi,
Trying to use the plugin, but each time when there is a code like this

```
<% @document.page.number %>
```
 I get the following error:

```
warning: Something went wrong while rendering: blog.html.eco
Cannot read property 'number' of undefined
error: Something went wrong with the action
error: An error occured: 
TypeError: Cannot read property 'number' of undefined
  at Object.eval (<anonymous>:45:25)
  at Object.eval (<anonymous>:65:8)
  at eval (<anonymous>:67:6)
  at Function.eco.render (/Users/antone/Sites/balupton/node_modules/docpad-plugin-eco/node_modules/eco/lib/index.js:26:25)
  at EcoPlugin.render (/Users/antone/Sites/balupton/node_modules/docpad-plugin-eco/out/eco.plugin.js:24:32)
  at ambi (/Users/antone/Sites/balupton/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:25:27)
  at Task.<anonymous> (/Users/antone/Sites/balupton/node_modules/docpad/node_modules/event-emitter-grouped/out/lib/event-emitter-grouped.js:45:23)
  at ambi (/Users/antone/Sites/balupton/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:23:18)
  at fire (/Users/antone/Sites/balupton/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:163:25)
  at b (domain.js:183:18)
  at Domain.run (domain.js:123:23)
  at Task.fire (/Users/antone/Sites/balupton/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:173:25)
  at processImmediate [as _immediateCallback] (timers.js:330:15)
```

What am I doing wrong?
I couldn't find what should I add to the docpad.coffee to make it working.
I use:

```
posts: ->
	@getCollection('documents').findAllLive({relativeOutDirPath:'blog'},[date:-1])
```

**Comment by StormPooper** [comment]
@ephimoff did @everthis' suggestion of adding `isPaged: true` fix it for you?

**Comment by StormPooper** [comment]
I'm closing this due to the amount of time that's passed with no word on if it's fixed, but if it's not, please comment and I'll reopen it.
